"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var inversify_1 = require("inversify");
exports.Container = inversify_1.Container;
exports.injectable = inversify_1.injectable;
exports.decorate = inversify_1.decorate;
exports.optional = inversify_1.optional;
exports.inject = inversify_1.inject;
exports.LazyServiceIdentifer = inversify_1.LazyServiceIdentifer;
var Injectable = inversify_1.injectable;
exports.Injectable = Injectable;
var Inject = inversify_1.inject;
exports.Inject = Inject;
var Decorate = inversify_1.decorate;
exports.Decorate = Decorate;
var Optional = inversify_1.optional;
exports.Optional = Optional;
